version: 4.0.2
options:
  debug: true
  hooking:
    mcmmo: false
  give-mobs-names: false
  give-all-mobs-names: false
  display-mob-equipment: true
  can-mobs-pick-up-equipment: false
  blank-mob-spawn:
    enabled: false
    skeletons-spawn-without-bow: false
multiworld:
  enabled-worlds:
  - world
drops:
  item-chance: 0.25
  socket-gem-chance: 0.2
  identity-tome-chance: 0.1
  custom-item-chance: 0.1
  unidentified-item-chance: 0.1
components:
  creature-spawning-enabled: true
  repairing-enabled: true
  socketting-enabled: true
  identifying-enabled: true
  distance-zones-enabled: false
  populating-enabled: false
display:
  item-display-name-format: '%generalprefix% %itemtype%'
  tooltip-format:
  - '&7Type: %mythicmaterial%'
  - '&7Tier:%tiercolor% %tiername%'