version: "1.0.0-B"
playSounds: true
messages:
  cannot-use: '&6[MythicDrops] &CYou cannot repair that item! Repairing cancelled!'
  do-not-have: '&6[MythicDrops] &CYou do not have enough materials to repair that item!'
  success: '&6[MythicDrops] &AYou successfully repaired your item!'
  instructions: '&6[MythicDrops] &APunch the anvil with this item again to repair it!'
repair-costs:
  wood-axe:
    material-name: WOOD_AXE
    costs:
      default:
        material-name: WOOD
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  wood-hoe:
    material-name: WOOD_HOE
    costs:
      default:
        material-name: WOOD
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  wood-pickaxe:
    material-name: WOOD_PICKAXE
    costs:
      default:
        material-name: WOOD
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  wood-spade:
    material-name: WOOD_SPADE
    costs:
      default:
        material-name: WOOD
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  wood-sword:
    material-name: WOOD_SWORD
    costs:
      default:
        material-name: WOOD
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  bow:
    material-name: BOW
    costs:
      default:
        material-name: WOOD
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  fishing-rod:
    material-name: FISHING_ROD
    costs:
      default:
        material-name: WOOD
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  stone-axe:
    material-name: STONE_AXE
    costs:
      default:
        material-name: STONE
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  stone-pickaxe:
    material-name: STONE_PICKAXE
    costs:
      default:
        material-name: STONE
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  stone-hoe:
    material-name: STONE_HOE
    costs:
      default:
        material-name: STONE
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  stone-sword:
    material-name: STONE_SWORD
    costs:
      default:
        material-name: STONE
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  stone-spade:
    material-name: STONE_SPADE
    costs:
      default:
        material-name: STONE
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  gold-axe:
    material-name: GOLD_AXE
    costs:
      default:
        material-name: GOLD_INGOT
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  gold-boots:
    material-name: GOLD_BOOTS
    costs:
      default:
        material-name: GOLD_INGOT
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  gold-chestplate:
    material-name: GOLD_CHESTPLATE
    costs:
      default:
        material-name: GOLD_INGOT
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  gold-helmet:
    material-name: GOLD_HELMET
    costs:
      default:
        material-name: GOLD_INGOT
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  gold-leggings:
    material-name: GOLD_LEGGINGS
    costs:
      default:
        material-name: GOLD_INGOT
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  gold-pickaxe:
    material-name: GOLD_PICKAXE
    costs:
      default:
        material-name: GOLD_INGOT
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  gold-hoe:
    material-name: GOLD_HOE
    costs:
      default:
        material-name: GOLD_INGOT
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  gold-spade:
    material-name: GOLD_SPADE
    costs:
      default:
        material-name: GOLD_INGOT
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  gold-sword:
    material-name: GOLD_SWORD
    costs:
      default:
        material-name: GOLD_INGOT
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  iron-axe:
    material-name: IRON_AXE
    costs:
      default:
        material-name: IRON_INGOT
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  iron-boots:
    material-name: IRON_BOOTS
    costs:
      default:
        material-name: IRON_INGOT
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  iron-chestplate:
    material-name: IRON_CHESTPLATE
    costs:
      default:
        material-name: IRON_INGOT
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  iron-helmet:
    material-name: IRON_HELMET
    costs:
      default:
        material-name: IRON_INGOT
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  iron-leggings:
    material-name: IRON_LEGGINGS
    costs:
      default:
        material-name: IRON_INGOT
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  iron-pickaxe:
    material-name: IRON_PICKAXE
    costs:
      default:
        material-name: IRON_INGOT
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  iron-hoe:
    material-name: IRON_HOE
    costs:
      default:
        material-name: IRON_INGOT
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  iron-spade:
    material-name: IRON_SPADE
    costs:
      default:
        material-name: IRON_INGOT
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  iron-sword:
    material-name: IRON_SWORD
    costs:
      default:
        material-name: IRON_INGOT
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  diamond-axe:
    material-name: DIAMOND_AXE
    costs:
      default:
        material-name: DIAMOND
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  diamond-boots:
    material-name: DIAMOND_BOOTS
    costs:
      default:
        material-name: DIAMOND
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  diamond-chestplate:
    material-name: DIAMOND_CHESTPLATE
    costs:
      default:
        material-name: DIAMOND
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  diamond-helmet:
    material-name: DIAMOND_HELMET
    costs:
      default:
        material-name: DIAMOND
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  diamond-hoe:
    material-name: DIAMOND_HOE
    costs:
      default:
        material-name: DIAMOND
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  diamond-leggings:
    material-name: DIAMOND_LEGGINGS
    costs:
      default:
        material-name: DIAMOND
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  diamond-pickaxe:
    material-name: DIAMOND_PICKAXE
    costs:
      default:
        material-name: DIAMOND
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  diamond-spade:
    material-name: DIAMOND_SPADE
    costs:
      default:
        material-name: DIAMOND
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  diamond-sword:
    material-name: DIAMOND_SWORD
    costs:
      default:
        material-name: DIAMOND
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  leather-boots:
    material-name: LEATHER_BOOTS
    costs:
      default:
        material-name: LEATHER
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  leather-chestplate:
    material-name: LEATHER_CHESTPLATE
    costs:
      default:
        material-name: LEATHER
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  leather-helmet:
    material-name: LEATHER_HELMET
    costs:
      default:
        material-name: LEATHER
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  leather-leggings:
    material-name: LEATHER_LEGGINGS
    costs:
      default:
        material-name: LEATHER
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  chainmail-boots:
    material-name: CHAINMAIL_BOOTS
    costs:
      default:
        material-name: IRON_FENCE
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  chainmail-chestplate:
    material-name: CHAINMAIL_CHESTPLATE
    costs:
      default:
        material-name: IRON_FENCE
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  chainmail-helmet:
    material-name: CHAINMAIL_HELMET
    costs:
      default:
        material-name: IRON_FENCE
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1
  chainmail-leggings:
    material-name: CHAINMAIL_LEGGINGS
    costs:
      default:
        material-name: IRON_FENCE
        priority: 0
        amount: 1
        experience-cost: 0
        repair-per-cost: 0.1